export const GET_USER_DATA = "GET_USER_DATA"
export const CREATE_ACTIVE_LINK = "CREATE_ACTIVE_LINK"
export const HAMBURGER_ICON_CLICK = 'HAMBURGER_ICON_CLICK'
export const GET_TEAM_VIEW_USER_DATA = "GET_TEAM_VIEW_USER_DATA"
export const TEAM_VIEW_USER_CLICK = "TEAM_VIEW_USER_CLICK"
export const GET_CLICKED_TEAM_USER_DATA = "GET_CLICKED_TEAM_USER_DATA"
export const GET_TEAM_VIEW_ORG_DATA = "GET_TEAM_VIEW_ORG_DATA"
export const STORE_CLICKED_USER_ID = "STORE_CLICKED_USER_ID"
export const CHANGE_LOADER_STATUS = "CHANGE_LOADER_STATUS"
export const GET_CLICKED_TEAM_USER_REPORTEE_DATA = "GET_CLICKED_TEAM_USER_REPORTEE_DATA"
export const GET_BACK_MANAGER_DATA = "GET_BACK_MANAGER_DATA"
export const IMPORT_USERS_POPUP_VISIBILITY = 'IMPORT_USERS_POPUP_VISIBILITY'
export const DOWNLOAD_SAMPLE_EXCEL = 'DOWNLOAD_SAMPLE_EXCEL'
export const GET_UPLOAD_FIELDS_DETAILS = 'GET_UPLOAD_FIELDS_DETAILS'
export const UPLOAD_IMPORT_USERS_POPUP_VISIBILITY = 'UPLOAD_IMPORT_USERS_POPUP_VISIBILITY'
export const PATCH_IMPORT_USERS_DATA = 'PATCH_IMPORT_USERS_DATA'
export const COMMON_ACTION = 'COMMON_ACTION'

export const GET_CONSOLE_USER_DATA = "GET_CONSOLE_USER_DATA"
export const COMMON_CONSOLE_ACTION = "COMMON_CONSOLE_ACTION"
export const TABLE_COLUMN_SETTING_DATA = "TABLE_COLUMN_SETTING_DATA"
export const ADD_USER_DATA_FORM = "ADD_USER_DATA_FORM"

export const GET_DEPARTMENTS_DATA = 'GET_DEPARTMENTS_DATA'
export const GET_ADDABLE_USERS_DATA = 'GET_ADDABLE_USERS_DATA'
export const GET_TABLE_COLUMN = 'GET_TABLE_COLUMN'
export const COMMON_DEPARTMENT_ACTION = 'COMMON_DEPARTMENT_ACTION'
export const GET_DEPT_TABLE_COLUMN_DATA = 'GET_DEPT_TABLE_COLUMN_DATA'
export const POST_CREATE_DEPARTMENT_DATA = 'POST_CREATE_DEPARTMENT_DATA'
export const POST_ADD_SELECTED_USERS_DATA = 'POST_ADD_SELECTED_USERS_DATA'
export const GET_ADD_SELECTED_USERS_POSTED_DATA = 'GET_ADD_SELECTED_USERS_POSTED_DATA'
export const GET_COMMON_VIEW_HEADER_NAME = 'GET_COMMON_VIEW_HEADER_NAME'
export const GET_DEPARTMENTS_SUGGESTION_DATA = 'GET_DEPARTMENTS_SUGGESTION_DATA';
export const EDIT_USER_DATA_FORM = 'EDIT_USER_DATA_FORM';




export const GET_DESIGNATIONS_DATA = "GET_DESIGNATIONS_DATA"
export const COMMON_DESIGNATION_ACTION = "COMMON_DESIGNATION_ACTION"


export const GET_CIRCLES_DATA = "GET_CIRCLES_DATA"
export const GET_CUSTOM_FIELDS_DATA = "GET_CUSTOM_FIELDS_DATA"
export const GET_CIRCLE_SUGGESTION_DATA = "GET_CIRCLE_SUGGESTION_DATA"
export const GET_SINGLE_FIELD_DATA = "GET_SINGLE_FIELD_DATA"


export const GET_SINGLE_VIEW_DATA = "GET_SINGLE_VIEW_DATA"
export const GET_SINGLE_VIEW_SUGGESTION_DATA = "GET_SINGLE_VIEW_SUGGESTION_DATA"
export const POST_COMMON_CREATE_DATA = "POST_COMMON_CREATE_DATA"
export const COMMON_ACTION_FOR_COMMON_REDUCER = "COMMON_ACTION_FOR_COMMON_REDUCER"
export const PATCH_COMMON_CREATE_DATA = "PATCH_COMMON_CREATE_DATA"

export const COMMON_HOLIDAY_ACTION = "COMMON_HOLIDAY_ACTION"
export const GET_HOLIDAY_TABLE_COLUMN_DATA = "GET_HOLIDAY_TABLE_COLUMN_DATA"
export const GET_HOLIDAY_PROFILES_DATA = "GET_HOLIDAY_PROFILES_DATA"





export const POST_COMMON_ACTION_ON_USER = "POST_COMMON_ACTION_ON_USER" // post actions like delete, activate or deactivate

export const GET_LOGIN_SESSION_DATA = "GET_LOGIN_SESSION_DATA" //for login session api

export const PATCH_TABLE_COLUMN_SETTING = "PATCH_TABLE_COLUMN_SETTING" //for patching the saved table column setting data

export const POST_COMMON_ADD_SELECTED_USERS_DATA = "POST_COMMON_ADD_SELECTED_USERS_DATA"

export const POST_COMMON_REMOVE_PEOPLE = "POST_COMMON_REMOVE_PEOPLE"

export const POST_COMMON_DELETE = "POST_COMMON_DELETE"




//Add Users Form
export const GET_ADD_USERS_PROFILE_DATA = "GET_ADD_USERS_PROFILE_DATA"