export const GET_USER_DATA = "GET_USER_DATA"
export const CREATE_ACTIVE_LINK = "CREATE_ACTIVE_LINK"
export const HAMBURGER_ICON_CLICK = 'HAMBURGER_ICON_CLICK'
export const GET_TEAM_VIEW_USER_DATA = "GET_TEAM_VIEW_USER_DATA"
export const TEAM_VIEW_USER_CLICK = "TEAM_VIEW_USER_CLICK"
export const GET_CLICKED_TEAM_USER_DATA = "GET_CLICKED_TEAM_USER_DATA"
export const GET_TEAM_VIEW_ORG_DATA = "GET_TEAM_VIEW_ORG_DATA"
export const STORE_CLICKED_USER_ID = "STORE_CLICKED_USER_ID"
export const CHANGE_LOADER_STATUS = "CHANGE_LOADER_STATUS"
export const GET_CLICKED_TEAM_USER_REPORTEE_DATA = "GET_CLICKED_TEAM_USER_REPORTEE_DATA"
export const GET_BACK_MANAGER_DATA = "GET_BACK_MANAGER_DATA"
export const IMPORT_USERS_POPUP_VISIBILITY = 'IMPORT_USERS_POPUP_VISIBILITY'
export const DOWNLOAD_SAMPLE_EXCEL = 'DOWNLOAD_SAMPLE_EXCEL'
export const GET_UPLOAD_FIELDS_DETAILS = 'GET_UPLOAD_FIELDS_DETAILS'

export const GET_TABLE_COLUMN_DATA = "GET_TABLE_COLUMN_DATA"
export const GET_CONSOLE_USER_DATA = "GET_CONSOLE_USER_DATA"
export const COMMON_CONSOLE_ACTION = "COMMON_CONSOLE_ACTION"
export const TABLE_COLUMN_SETTING_DATA = "TABLE_COLUMN_SETTING_DATA"


